# Generated by Django 6.0 on 2025-12-20 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopTrackSnapshot',
            new_name='TopTracksSnapshot',
        ),
    ]
