# Generated by Django 6.0 on 2026-01-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_analyzer', '0002_rename_toptracksnapshot_toptrackssnapshot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopTracksSnapshot',
            new_name='TopTrackSnapshot',
        ),
        migrations.AlterModelOptions(
            name='toptracksnapshot',
            options={'ordering': ['-fetched_at']},
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='refresh_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
